package com.orbita.rokclone;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffXfermode;
import android.util.AttributeSet;
import android.view.MotionEvent;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import java.util.ArrayList;
import java.util.List;

public class GameView extends SurfaceView implements SurfaceHolder.Callback {
    private GameThread thread;
    private MainActivity activity;

    // Assets
    private Bitmap bmpGrass, bmpTownHall, bmpFarm;

    // Camera Panning
    private float camX = 200f;
    private float camY = 500f;
    private float lastTouchX, lastTouchY;

    // Map Settings
    private final int MAP_SIZE = 15;
    private final int TILE_WIDTH = 256;
    private final int TILE_HEIGHT = 128;

    // Buildings
    private static class Building {
        String type;
        int gridX, gridY;
        Building(String t, int x, int y) { type = t; gridX = x; gridY = y; }
    }
    private List<Building> buildings = new ArrayList<>();
    private String buildMode = null;

    private Paint paintScreen = new Paint();

    public GameView(Context context, AttributeSet attrs) {
        super(context, attrs);
        getHolder().addCallback(this);

        // Load Real High-Res Assets generated by AI
        bmpGrass = BitmapFactory.decodeResource(getResources(), R.drawable.tile_grass);
        bmpTownHall = BitmapFactory.decodeResource(getResources(), R.drawable.bld_townhall);
        bmpFarm = BitmapFactory.decodeResource(getResources(), R.drawable.bld_farm);

        // Scale assets to fit our tile grid optimally
        bmpGrass = Bitmap.createScaledBitmap(bmpGrass, TILE_WIDTH, TILE_WIDTH, true);
        bmpTownHall = Bitmap.createScaledBitmap(bmpTownHall, 300, 300, true);
        bmpFarm = Bitmap.createScaledBitmap(bmpFarm, 200, 200, true);

        // Use Screen blending to remove the pure black backgrounds generated by AI 
        // without heavy alpha channel processing.
        paintScreen.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SCREEN));

        // Initial TownHall
        buildings.add(new Building("townhall", 7, 7));
    }

    public void setActivity(MainActivity act) { this.activity = act; }
    
    public void enterBuildMode(String type) { this.buildMode = type; }
    
    public int getBuildingCount(String type) {
        int c = 0;
        for(Building b : buildings) { if(b.type.equals(type)) c++; }
        return c;
    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        thread = new GameThread(getHolder(), this);
        thread.setRunning(true);
        thread.start();
    }

    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {}

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {
        boolean retry = true;
        thread.setRunning(false);
        while (retry) {
            try { thread.join(); retry = false; } catch (InterruptedException e) {}
        }
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        float x = event.getX();
        float y = event.getY();

        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                lastTouchX = x;
                lastTouchY = y;
                break;
                
            case MotionEvent.ACTION_MOVE:
                float dx = x - lastTouchX;
                float dy = y - lastTouchY;
                camX += dx;
                camY += dy;
                lastTouchX = x;
                lastTouchY = y;
                break;
                
            case MotionEvent.ACTION_UP:
                // If it was a quick tap (not dragged much) -> handle building placement
                if (buildMode != null) {
                    float adjX = x - camX;
                    float adjY = y - camY;
                    
                    int gX = (int) Math.floor((adjX / (TILE_WIDTH / 2.0f) + adjY / (TILE_HEIGHT / 2.0f)) / 2.0f);
                    int gY = (int) Math.floor((adjY / (TILE_HEIGHT / 2.0f) - adjX / (TILE_WIDTH / 2.0f)) / 2.0f);

                    if (gX >= 0 && gX < MAP_SIZE && gY >= 0 && gY < MAP_SIZE) {
                        boolean occupied = false;
                        for(Building b : buildings) {
                            if(b.gridX == gX && b.gridY == gY) occupied = true;
                        }
                        
                        if (!occupied) {
                            if (activity.spendWood(100)) {
                                buildings.add(new Building(buildMode, gX, gY));
                                buildMode = null;
                            }
                        }
                    }
                }
                break;
        }
        return true;
    }

    public void draw(Canvas canvas) {
        super.draw(canvas);
        if (canvas == null) return;

        // Space/Void background
        canvas.drawColor(Color.parseColor("#111111"));

        // Render Ground Tiles
        for (int x = 0; x < MAP_SIZE; x++) {
            for (int y = 0; y < MAP_SIZE; y++) {
                float px = camX + (x - y) * (TILE_WIDTH / 2f);
                float py = camY + (x + y) * (TILE_HEIGHT / 2f);

                // Culling: Don't draw if outside screen
                if (px < -300 || px > getWidth() + 300 || py < -300 || py > getHeight() + 300) continue;

                // Draw grass tile
                canvas.drawBitmap(bmpGrass, px - (TILE_WIDTH / 2f), py - (TILE_HEIGHT / 2f), paintScreen);
            }
        }

        // Sort buildings by Y depth for correct isometric overlapping
        List<Building> sorted = new ArrayList<>(buildings);
        sorted.sort((b1, b2) -> Integer.compare(b1.gridX + b1.gridY, b2.gridX + b2.gridY));

        for (Building b : sorted) {
            float px = camX + (b.gridX - b.gridY) * (TILE_WIDTH / 2f);
            float py = camY + (b.gridX + b.gridY) * (TILE_HEIGHT / 2f);

            Bitmap bImg = b.type.equals("townhall") ? bmpTownHall : bmpFarm;
            
            // Adjust to align building bottom with the tile center
            canvas.drawBitmap(bImg, px - (bImg.getWidth() / 2f), py - bImg.getHeight() + (TILE_HEIGHT / 1.5f), paintScreen);
        }
    }
}

class GameThread extends Thread {
    private SurfaceHolder surfaceHolder;
    private GameView gameView;
    private boolean running;

    public GameThread(SurfaceHolder surfaceHolder, GameView gameView) {
        this.surfaceHolder = surfaceHolder;
        this.gameView = gameView;
    }
    public void setRunning(boolean isRunning) { running = isRunning; }

    @Override
    public void run() {
        while (running) {
            Canvas canvas = null;
            try {
                canvas = this.surfaceHolder.lockCanvas();
                synchronized(surfaceHolder) {
                    this.gameView.draw(canvas);
                }
            } catch (Exception e) {} 
            finally {
                if (canvas != null) {
                    try { surfaceHolder.unlockCanvasAndPost(canvas); } catch (Exception e) {}
                }
            }
        }
    }
}
